export const UI_MESSAGE_TIMEOUT_MS = 5_000;
export const STUCK_CHECK_INTERVAL_DIVISOR = 4;
export const MAX_STUCK_CHECK_INTERVAL_MS = 30_000;
export const VERIFICATION_OUTPUT_MAX_LENGTH = 2_000;
export const VERIFICATION_CONTEXT_MAX_LENGTH = 1_000;
export const FORCE_KILL_TIMEOUT_MS = 500;
export const DEFAULT_DAEMON_STOP_TIMEOUT_MS = 5_000;
export const PROCESS_EXIT_TIMEOUT_MS = 30_000;

export const MESSAGE_DISMISS_TIMEOUT_MS = 3_000;
export const STATUS_MESSAGE_TIMEOUT_MS = 2_000;
export const TRANSITION_DELAY_MS = 800;
export const RESTART_MESSAGE_TIMEOUT_MS = 2_000;

export const AGENT_OUTPUT_PREVIEW_MAX_CHARS = 500;
export const PHASE_DETECTION_OUTPUT_WINDOW_CHARS = 2_000;

export const PROGRESS_COLOR_THRESHOLD_COMPLETE = 100;
export const PROGRESS_COLOR_THRESHOLD_HIGH = 75;
export const PROGRESS_COLOR_THRESHOLD_MEDIUM = 50;

export const CLI_SEPARATOR_WIDTH = 60;
export const TASK_LIST_SEPARATOR_WIDTH = 70;
export const DRY_RUN_SEPARATOR_WIDTH = 50;

export const OUTPUT_THROTTLE_MS = 100;
export const PROCESS_POLL_INTERVAL_MS = 100;
export const GIT_STATS_POLL_INTERVAL_MS = 5_000;

export const DRY_RUN_CONFIG_VALIDATION_DELAY_MS = 500;
export const DRY_RUN_PRD_LOAD_DELAY_MS = 300;
export const DRY_RUN_ITERATION_DELAY_MS = 800;
export const DRY_RUN_TASK_DELAY_MS = 500;

export const ITERATION_FILENAME_PADDING = 3;
export const LOG_LEVEL_TAG_WIDTH = 7;

export const SIMILARITY_THRESHOLD = 0.7;
export const FAILURE_CATEGORY_THRESHOLD_PERCENTAGE = 40;
export const MIN_TASK_FAILURES_FOR_RECOMMENDATION = 5;
export const PERCENTAGE_BAR_SCALE_DIVISOR = 5;
export const CATEGORY_NAME_PAD_WIDTH = 18;

export const OUTPUT_BUFFER_END_RATIO = 0.7;

export const MS_PER_MINUTE = 60_000;
export const MS_PER_HOUR = 3_600_000;
export const MS_PER_DAY = 86_400_000;
export const DAYS_PER_MONTH = 30;
