export const UI_MESSAGE_TIMEOUT_MS = 5_000;
export const STUCK_CHECK_INTERVAL_DIVISOR = 4;
export const MAX_STUCK_CHECK_INTERVAL_MS = 30_000;
export const VERIFICATION_OUTPUT_MAX_LENGTH = 2_000;
export const VERIFICATION_CONTEXT_MAX_LENGTH = 1_000;
export const FORCE_KILL_TIMEOUT_MS = 500;
export const DEFAULT_DAEMON_STOP_TIMEOUT_MS = 5_000;
export const PROCESS_EXIT_TIMEOUT_MS = 30_000;
