export const UI_MESSAGE_TIMEOUT_MS = 5000;
export const STUCK_CHECK_INTERVAL_DIVISOR = 4;
export const MAX_STUCK_CHECK_INTERVAL_MS = 30000;
export const VERIFICATION_OUTPUT_MAX_LENGTH = 2000;
export const VERIFICATION_CONTEXT_MAX_LENGTH = 1000;
export const FORCE_KILL_TIMEOUT_MS = 500;
export const DEFAULT_DAEMON_STOP_TIMEOUT_MS = 5000;
